### ISSUE TITLE
How to use yii2-jalali-daterangepicker as a filter in Yii2 Gridview?

### ISSUE THREAD

**Issue by amirzaghari** [faravaghi/yii2-jalali-daterangepicker#1]
Can we use this date range picker as a filter in gridview widget?

**Comment by faravaghi** [comment]
Hi @amirzaghari yes you can.
sample:
```php
[
	'attribute' => 'publish_up',
	'enableSorting'=>false,
	'filter' => \faravaghi\jalaliDateRangePicker\jalaliDateRangePicker::widget([
		'model'	 => $searchModel,
		'attribute' => 'publish_up',
		'options'  => [
			'format' => 'jYYYY/jMM/jDD',
			'viewformat' => 'jYYYY/jMM/jDD',
			// 'minDate' => '1394/10/17',
			'placement' => 'right',
			'opens' => 'left',
			'showDropdowns'=> true,
			// 'timePicker' => true,
			// 'timePicker24Hour' => true,
			'locale'=>[
				'format'=> 'jYYYY/jMM/jDD',
				'separator'=> ' - ',
				'applyLabel'=> Yii::t('zii', 'Apply'),
				'cancelLabel' => Yii::t('zii', 'Cancel'),
				'fromLabel' => Yii::t('zii', 'From'),
				'toLabel' => Yii::t('zii', 'To'),
				'customRangeLabel' => 'Custom',
				'daysOfWeek'=>[
					'یک',
					'دو',
					'سه',
					'چهار',
					'پنج',
					'جمعه',
					'شنبه',
				],
				'monthNames'=>[
					'فروردین',
					'اردیبهشت',
					'خرداد',
					'تیر',
					'مرداد',
					'شهریور',
					'مهر',   
					'آبان',
					'آذر',
					'دی',
					'بهمن',
					'اسفند',
				],
				'firstDay' => 6
			],
		],
		'htmlOptions' => [
			'class'	=> 'form-control',
		]
	]),
]
```

**Comment by amirzaghari** [comment]
Thanks @faravaghi but this code always submit "Today Date" in filter input! How should I set it's default value to NULL? 
and How should I convert it's value to Gregorian date?

**Comment by faravaghi** [comment]
Please download last version and write this:
```php
[
	'attribute' => 'publish_up',
	'enableSorting'=>false,
	'filter' => \faravaghi\jalaliDateRangePicker\jalaliDateRangePicker::widget([
		'model'	 => $searchModel,
		'attribute' => 'publish_up',
		'options'  => [
			'format' => 'jYYYY/jMM/jDD',
			'viewformat' => 'jYYYY/jMM/jDD',
			// 'minDate' => '1394/10/17',
			'placement' => 'right',
			'autoUpdateInput' => false,
			'opens' => 'left',
			'showDropdowns'=> true,
			// 'timePicker' => true,
			// 'timePicker24Hour' => true,
			'locale'=>[
				'format'=> 'jYYYY/jMM/jDD',
				'separator'=> ' - ',
				'applyLabel'=> Yii::t('zii', 'Apply'),
				'cancelLabel' => Yii::t('zii', 'Clear'),
				'fromLabel' => Yii::t('zii', 'From'),
				'toLabel' => Yii::t('zii', 'To'),
				'customRangeLabel' => 'Custom',
				'daysOfWeek'=>[
					'یک',
					'دو',
					'سه',
					'چهار',
					'پنج',
					'جمعه',
					'شنبه',
				],
				'monthNames'=>[
					'فروردین',
					'اردیبهشت',
					'خرداد',
					'تیر',
					'مرداد',
					'شهریور',
					'مهر',   
					'آبان',
					'آذر',
					'دی',
					'بهمن',
					'اسفند',
				],
				'firstDay' => 6
			],
		],
		'events' => [
			'apply.daterangepicker' => new yii\web\JsExpression("function(ev, picker) {
				$(this).val(picker.startDate.format('YYYY/MM/DD') + ' - ' + picker.endDate.format('YYYY/MM/DD'));
			}"),
			'cancel.daterangepicker' => new yii\web\JsExpression("function(ev, picker) {
				$(this).val('');
			}"),
		],
		'htmlOptions' => [
			'class'	=> 'form-control',
			'value' => '',
		]
	]),
],
```

**Comment by faravaghi** [comment]
in "apply.daterangepicker" event if set 'jYYYY/jMM/jDD' format convert to persian date.

**Comment by amirzaghari** [comment]
I installed the last version and also I added your suggested 'events'! But I cant leave blank the dateRangePicker! when I press cancel button it sends Today value! how should I fix that?

**Comment by amirzaghari** [comment]
@faravaghi any idea?
when I click apply button events worked but it submits the "today value" not my selection and don't convert format!!

**Comment by faravaghi** [comment]
Find this problem in GridView's structure. this widget works correctly. You must stop sending the form and submit your correct date manually.
You can also convert persian date by using [Jalali date & time extension for yii2](https://github.com/mohammad-mahdy/yii2-jdate)

**Comment by amirzaghari** [comment]
@faravaghi Is there an option to set default value in filter input? My gridview is working correctly and dateRange field is not required in my search model but the dateRangePicker always sends today value!  Even when I clear input!

**Comment by amirzaghari** [comment]
سلام
شاید من منظورم رو بد رسونده باشم توی کامنت ها!!
در واقع فیلتر تاریخ درست کار میکنه اما مقدار فیلتر رو نمیشه خالی کرد و
همیشه تاریخ امروز رو به عنوان فیلتر توی ورودی نمایش میده! راهی هست که یک
مقدار null برای شروع کار بهش داد تا چیزی به عنوان بازه زمانی ارسال نشه؟

**Comment by faravaghi** [comment]
@amirzaghari Please visit [line 56](https://github.com/faravaghi/yii2-jalali-daterangepicker/blob/6faf48a21d8856d12f5240c88a3b997c52c1a193/assets/js/daterangepicker.js#L56), This variable is used to empty the initial value that in new update added for your request.

**Comment by amirzaghari** [comment]
Thanks @faravaghi , How could I use this in options? 
('autoUpdateInput' => true) not wordked!

**Comment by faravaghi** [comment]
set **false** for null in initial value, Please **_carefully look at_** the above sample. 
```php
'autoUpdateInput' => false,
```
